Models/Category.cs
using System.Collections.Generic;

public class Category
{
    public int CategoryId { get; set; }
    public string CategoryName { get; set; }
    public string Description { get; set; }
    public ICollection<Product> Products { get; set; }
 }

Models/Customer.cs
using System;
using System.ComponentModel.DataAnnotations.Schema;

public class Customer
{
    public int CustomerId { get; set; }
    public string CompanyName { get; set; }
    public string Address { get; set; }
    public string City { get; set; }
    public string Region { get; set; }
    public string PostalCode { get; set; }
    public string Country { get; set; }
    public string Phone { get; set; }
    public string Fax { get; set; }
}

Models/DataContext.cs
using Microsoft.EntityFrameworkCore;

public class DataContext : DbContext
{
    public DataContext(DbContextOptions<DataContext> options) : base(options) { }

    public DbSet<Category> Categories { get; set; }
    public DbSet<Product> Products { get; set; }
    public DbSet<Discount> Discounts { get; set; }
    public DbSet<Customer> Customers { get; set; }
    public void AddCustomer(Customer customer)
    {
        this.Add(customer);
        this.SaveChanges();
    }
}

Models/Discount.cs
using System.ComponentModel.DataAnnotations.Schema;
public class Discount
{
  public int DiscountId { get; set; }
  public int Code { get; set; }
  public DateTime StartTime { get; set; }
  public DateTime EndTime { get; set; }
  public int ProductId { get; set; }
  [Column(TypeName = "decimal(4,4)")]
  public decimal DiscountPercent { get; set; }
  public string Title { get; set; }
  public string Description { get; set; }

  public Product Product { get; set; }
}

Models/Product.cs
using System;
using System.ComponentModel.DataAnnotations.Schema;

public class Product
{
    public int ProductId { get; set; }
    public string ProductName { get; set; }
    public string QuantityPerUnit { get; set; }
    [Column(TypeName = "decimal(18,4)")]
    public decimal UnitPrice { get; set; }
    public short UnitsInStock { get; set; }
    public short UnitsOnOrder { get; set; }
    public short ReorderLevel { get; set; }
    public bool Discontinued { get; set; }
    public int CategoryId { get; set; }
    public Category Category { get; set; }
}

Models/ProductViewModel.cs
public class ProductViewModel
{
    public Category category { get; set; }
    public IEnumerable<Product> Products { get; set; }
}

Controllers/CustomerController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace Northwind.Controllers
{
    public class CustomerController : Controller
    {
        private DataContext _dataContext;
        public CustomerController(DataContext db) => _dataContext = db;
        public ActionResult Customer() => View(_dataContext.Customers.OrderBy(b => b.CompanyName));
        public IActionResult AddCustomer(int id)
        {
            ViewBag.CustomerId = id;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddCustomer(int id, Customer model)
        {
            if (ModelState.IsValid)
            {
                _dataContext.AddCustomer(model);
                return RedirectToAction("Customer");
            }
            @ViewBag.CustomerId = id;
            return View();
        }
    }
}

Controllers/DiscountController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace Northwind.Controllers
{
    public class DiscountController : Controller
    {
        private DataContext _dataContext;
        public DiscountController(DataContext db) => _dataContext = db;
        public ActionResult Discount() => View(_dataContext.Discounts.Where(d => d.StartTime <= DateTime.Now && d.EndTime > DateTime.Now));
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Northwind.Controllers
{
    public class HomeController : Controller
    {
        // this controller depends on the NorthwindRepository
        private DataContext _dataContext;
        public HomeController(DataContext db) => _dataContext = db;
        public ActionResult Index() => View(_dataContext.Discounts.Where(d => d.StartTime <= DateTime.Now && d.EndTime > DateTime.Now).Take(3));
    }
}

Controllers/ProductController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace Northwind.Controllers
{
    public class ProductController : Controller
    {
          // this controller depends on the BloggingRepository
        private DataContext _dataContext;
        public ProductController(DataContext db) => _dataContext = db;

        public ActionResult Category() => View(_dataContext.Categories.OrderBy(c => c.CategoryName));

        public IActionResult CategoryDetail(int id) => View(new ProductViewModel
        {
            category = _dataContext.Categories.FirstOrDefault(c => c.CategoryId == id),
            Products = _dataContext.Products.Where(p => p.ProductId == id)
        });
    }
}

Views/Customer/AddCustomer.cshtml
@model Customer

<div class="bg-primary m-1 p-1 text-white"><h4>Add Customer</div>

<form>
  <div class="form-group">
    <label asp-for="@Model.CustomerId">Customer ID</label>
    <input type="text" class="form-control" asp-for="@Model.CustomerId">
  </div>
  <div class="form-group">
    <label asp-for="@Model.CompanyName">Company Name</label>
    <input type="text" class="form-control" asp-for="@Model.CompanyName">
  </div>
  <div class="form-group">
    <label asp-for="@Model.Address">Address</label>
    <input asp-for="@Model.Address" type="text" class="form-control">
  </div>
  <div class="form-group">
    <label asp-for="@Model.City">City</label>
    <input asp-for="@Model.City" type="text" class="form-control">
  </div>
  <div class="form-group">
    <label asp-for="@Model.Region">Region</label>
    <input asp-for="@Model.Region" type="text" class="form-control">
  </div>
  <div class="form-group">
    <label asp-for="@Model.PostalCode">Postal Code</label>
    <input asp-for="@Model.PostalCode" type="text" class="form-control">
  </div>
  <div class="form-group">
    <label asp-for="@Model.Country">Country</label>
    <input asp-for="@Model.Country" type="text" class="form-control">
  </div>
  <div class="form-group">
    <label asp-for="@Model.Phone">Phone</label>
    <input asp-for="@Model.Phone" type="text" class="form-control">
  </div>
  <div class="form-group">
    <label asp-for="@Model.Fax">Fax</label>
    <input asp-for="@Model.Fax" type="text" class="form-control">
  </div>
  <button type="submit" class="btn btn-primary">Add Customer</button>
</form>

Views/Customer/customer.cshtml
@model IEnumerable<Customer>

<div class="bg-primary m-1 p-1 text-white"><h4>Customers</h4> <a asp-action="AddCustomer" asp-route-itemid=""><button type="button" class="btn btn-light">Add Customer</button></a></div>

@if (Model.Count() == 0)
{
    <p>There are no customers</p>
}
else
{
    <table class="table table-striped">
        <thead>
            <tr>
            <th scope="col">Company Name</th>
            <th scope="col">City</th>
            <th scope="col">Postal Code</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Customer customer in Model)
            {
                <tr>
                    <th scope="row">@customer.CompanyName</th>
                    <td>@customer.City</td>
                    <td>@customer.PostalCode</td>
                </tr>
            }
        </tbody>
    </table>
}

Views/Discount/discount.cshtml
@model IEnumerable<Discount>

<ul class="list-group">
  @foreach (Discount d in Model)
    {
        <li class="list-group-item"><b>@d.Title</b>: @d.Description | Discount expires: @d.EndTime.ToString("MM/dd/yyyy")</li>
    }
</ul>

Views/Home/index.cshtml
@model IEnumerable<Discount>
<div class="jumbotron my-2 border border-secondary">
    <h1 class="display-4">Northwind</h1>
    <p class="lead">We have the best prices and selection of high quality foods &amp; beverages on the planet! Check out our featured discounts below.</p>
    <hr class="my-4">
    <p>For exceptional international quisuine, look no further.</p>
    <a class="btn btn-outline-primary btn-lg" href="#" role="button">Order Now</a>
</div>

<div class="row row-cols-1 row-cols-lg-3">
    @foreach (Discount d in Model)
    {
        <div class="col discounts px-2 py-4">
            <h3>@d.Title</h3>
            <div class="mb-4 code1">
                @d.Description
            </div>
             <i>Discount expires: @d.EndTime.ToString("MM/dd/yyyy")</i><br />
            <a href="#" class="code" data-code="@d.Code" data-product="@d.Title"><i class="far fa-hand-point-right"></i> Discount Code</a>
        </div>
    }
</div>

<!-- toast -->
    <div class="position-fixed bottom-0 right-0 p-3" style="z-index: 5; right: 0; bottom: 0;">
        <div id="liveToast" class="toast hide" role="alert" aria-live="assertive" aria-atomic="true" data-delay="2000">
          <div class="toast-header">
            <strong id="toastHeader" class="mr-auto">Title</strong>
            <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="toast-body">
            Discount Code: <strong id="code">1234</strong>
          </div>
        </div>
    </div>

@section Scripts {<script type="text/javascript" src="Views/wwwroot/js/client.js"></script>}

Views/Product/CategoryDetail.cshtml
@model ProductViewModel

<div class="bg-primary m-1 p-1 text-white"><h4>@Model.category.CategoryName Details</h4></div>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Product Name</th>
      <th scope="col">Unit Price</th>
      <th scope="col">Units in Stock</th>
    </tr>
  </thead>
  <tbody>
    @foreach (Product product in Model.Products)
    {
        <tr>
            <th scope="row">@product.ProductName</th>
            <td>@product.UnitPrice</td>
            <td>@product.UnitsInStock</td>
        </tr>
    }
  </tbody>
</table>

Views/Product/category.cshtml
@model IEnumerable<Category>

<div>
    <ul class="list-group">
        @foreach (Category category in Model)
        {
            <li class="list-group-item"><a asp-action="CategoryDetail" asp-route-id="@category.CategoryId"><button type="button" class="btn btn-primary">@category.CategoryName</button></a></li>
        }
    </ul>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <!-- bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <!-- font awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- google font -->
    <link href="https://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet">
    <!-- client -->
    <link rel="stylesheet" href="~/css/client.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><i class="far fa-compass"></i> Northwind</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-database"></i> Products
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="Product" asp-action="Category"><i class="fas fa-list-ul"></i> Browse Categories</a>
                                <a class="dropdown-item" href="#"><i class="fas fa-search"></i> Product Search</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-controller="Discount" asp-action="Discount"><i class="fas fa-tag"></i> Current Discounts</a>
                            </div>
                        </li>
                        <li class="nav-item">
                             <a class="nav-link" asp-controller="Customer" asp-action="Customer"><i class="fas fa-users"></i> Customers</a>
                        </li>
                    </ul>
                </div>
                <form class="form-inline my-2 my-lg-0 d-none d-md-inline">
                    <input class="form-control mr-sm-2" type="search" placeholder="Product Search" aria-label="Search">
                    <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit"><i class="fas fa-search"></i><span class="sr-only">Search</span></button>
                </form>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Northwind
        </div>
    </footer>
    <!-- jquery -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <!-- bootstrap js -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    
    @RenderSection("Scripts", required: false)
</body>
</html>